### DISCUSSION TITLE
List component design proposals

### DISCUSSION THREAD

**Discussion by rrickgauer** [rrickgauer/lists#4] [Ideas]
This is for the front-end list component design proposals

**Comment by rrickgauer** [comment]
![image](https://user-images.githubusercontent.com/22210580/146010744-95297b01-91c4-44ee-944b-3b85b170595a.png)

**Comment by rrickgauer** [comment]
## HTML

```html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <link rel="stylesheet" href="css/style.css">

    <title>Hello, world!</title>
</head>

<body>

    <div class="d-flex" id="page">
        <section id="sidenav-container">
            <div id="sidenav">
                <div class="d-flex align-baseline justify-content-between">
                    <h3>Lists</h3>
                    <div>
                        <button type="button" class="btn btn-sm btn-secondary" onclick="closeSidenav()">X</button>
                    </div>
                </div>
                <div class="list-group" id="lists-container">
                    <button type="button" class="list-group-item list-group-item-action">
                        <div class="list-group-item-name">Cras justo odio ajs</div>
                        <span class="badge badge-primary badge-pill">14</span>
                    </button>
                </div>
            </div>
        </section>

        <section id="main" class="container-fluid">
            <h3>Main</h3>
            <button type="button" class="btn btn-primary" onclick="toggleSidenav()">Toggle sidenav</button>

            <div id="list-board" class="mt-5">
                <div class="card list">
                    <div class="card-header">
                        <span>List name here</span>
                        
                        <div class="list-header-buttons">
                            <div class="dropdown mr-2">
                                <button class="btn btn-sm btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">Menu</button>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <button class="dropdown-item" type="button">Action</button>
                                    <button class="dropdown-item" type="button">Another action</button>
                                    <button class="dropdown-item" type="button">Something else here</button>
                                </div>
                            </div>
    
                            <button type="button" class="close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    </div>

                    <div class="card-body">
                        <form>
                            <input class="form-control form-control-sm" type="text" placeholder="Add new item...">
                        </form>


                    </div>
                </div>
            </div>
        </section>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

    <script src="js/main.js"></script>

</body>

</html>
```

**Comment by rrickgauer** [comment]
## CSS

```scss
$sidenav-lg-width: 400px;

#sidenav-container {
    z-index: 110;
    width: 0px;
    margin-left: 0px;
    background-color: white;
    max-height: 100vh;
    overflow-y: hidden;
    position: fixed;
    top: 0;
    left: 0;
}

#page.sidenav-open #sidenav-container {
    width: 100vw;
}

// sidenav: don't take up full screen width for larger screens
@media screen and (min-width: 768px) {
    #page.sidenav-open #sidenav-container {
        width: $sidenav-lg-width;
    }
}

#sidenav {
    padding: 10px;
}

#lists-container {
    height: 95vh;
    overflow-y: auto;
    padding-bottom: 50px;

    .list-group-item {
        display: flex;
        justify-content: space-between;
        align-items: baseline;
    }

    .list-group-item-name {
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
    }
}

// sidenav overlay
.drawer-overlay {
    position: fixed;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
    overflow: hidden;
    z-index: 109;
    background-color: rgba(0,0,0,.2);
    animation: animation-drawer-fade-in .3s ease-in-out 1;
}

#main {
    padding: 10px;
}


#list-board {
    // padding: 20px;
}

.list {
    .card-header {
        background-color: inherit;
        display: flex;
        justify-content: space-between;
        align-items: baseline;

        .list-header-buttons {
            display: flex;
            align-items: baseline;
        }
    }
}
```
