### ISSUE TITLE
[Front-End]: create a color pallet

### ISSUE THREAD

**Issue by rrickgauer** [rrickgauer/lists#48]
Define custom color [maps](https://sass-lang.com/documentation/values/maps) in sass document

**Comment by rrickgauer** [comment]
Primary color


Name | Hue | Saturation | Lightness | CSS
--- | --- | --- | --- | ---
Darkest  | 221 | 95 | 5  | `hsl(221, 95%, 5%)`
Darker   | 221 | 87 | 25 | `hsl(221, 87%, 25%)`
Dark     | 221 | 79 | 45 | `hsl(221, 79%, 45%)`
Primary  | 221 | 71 | 65 | `hsl(221, 71%, 65%)`
Light    | 221 | 79 | 75 | `hsl(221, 79%, 75%)`
Lighter  | 221 | 87 | 85 | `hsl(221, 87%, 85%)`
Lightest | 221 | 95 | 85 | `hsl(221, 95%, 95%)`

**Comment by rrickgauer** [comment]
## Grey color

Name | Hue | Saturation | Lightness | CSS
--- | --- | --- | --- | ---
Darkest  | 223 | 10 | 5  | `hsl(223, 10%, 5%)`
Darker   | 223 | 10 | 25 | `hsl(223, 10%, 25%)`
Dark     | 223 | 10 | 45 | `hsl(223, 10%, 45%)`
Primary  | 223 | 10 | 65 | `hsl(223, 10%, 65%)`
Light    | 223 | 10 | 75 | `hsl(223, 10%, 75%)`
Lighter  | 223 | 10 | 85 | `hsl(223, 10%, 85%)`
Lightest | 223 | 10 | 95 | `hsl(223, 10%, 95%)`



```scss
// primary colors
$color-grey-darkest:  hsl(223, 95%, 5%);
$color-grey-darker:   hsl(223, 87%, 25%);
$color-grey-dark:     hsl(223, 79%, 45%);
$color-grey-primary:  hsl(223, 71%, 65%);
$color-grey-light:    hsl(223, 79%, 75%);
$color-grey-lighter:  hsl(223, 87%, 85%);
$color-grey-lightest: hsl(223, 95%, 95%);

// primary colors
.color-grey-darkest { color: $color-grey-darkest; }  
.color-grey-darker { color: $color-grey-darker; }   
.color-grey-dark { color: $color-grey-dark; }     
.color-grey-primary { color: $color-grey-primary; }  
.color-grey-light { color: $color-grey-light; }    
.color-grey-lighter { color: $color-grey-lighter; }  
.color-grey-lightest { color: $color-grey-lightest; }

// background colors
.bg-grey-darkest { background-color: $color-grey-darkest; }  
.bg-grey-darker { background-color: $color-grey-darker; }   
.bg-grey-dark { background-color: $color-grey-dark; }     
.bg-grey-primary { background-color: $color-grey-primary; }  
.bg-grey-light { background-color: $color-grey-light; }    
.bg-grey-lighter { background-color: $color-grey-lighter; }  
.bg-grey-lightest { background-color: $color-grey-lightest; }
```
